#! /usr/bin/env sh
#
usage="Usage: ble-backend [-command=start/changemesh/scan] [-command=on/off -mac=d74d38dabcf7]\n"

if [ $# -eq 0 ]; then
  printf "${usage}"
  exit 1
fi

while [ $# -gt 0 ]; do
  case $1 in
    --help|-h)
      printf "${usage}"
      exit 0
      ;;
    # --start)
    -command=start)
      echo '**start**'
      sleep 5
      exit 0
      ;;
    # --changemesh)
    -command=changemesh)
      echo '**changemesh**'
      sleep 5
      exit 0
      ;;
    # --scan)
    -command=scan)
      echo "**scan**"
      mysql -p123456 -e 'INSERT ge.tb_data_aging(device_type, factory, fw_version, rssi_ble, rssi_wifi, mac_ble, mac_wifi, is_qualified, is_sync, datetime) VALUES(5, 2, '3.1', -65, -33, "scantest", "scantest", true, false, now())'
      sleep 5
      exit 0
      ;;
    # turn on
    -command=on)
      shift
      mac=$(echo "$1" | awk -F= '{print $2}')
      echo "**turn on $mac**"
      sleep 1
      exit 0
      ;;
    # turn off
    -command=off)
      shift
      mac=$(echo "$1" | awk -F= '{print $2}')
      echo "**turn off $mac**"
      sleep 1
      exit 0
      ;;

    *)
      # continue
      shift
      ;;
  esac
  shift || true
done

printf "Invalid input\n"
printf "${usage}"
exit 1
