#! /usr/bin/env sh
#
usage="Usage: ble-backend [-command=start/changemesh/scan] [-command=on/off -mac=d74d38dabcf7]\n"

if [ $# -eq 0 ]; then
  printf "${usage}"
  exit 1
fi

while [ $# -gt 0 ]; do
  case $1 in
    --help|-h)
      printf "${usage}"
      exit 0
      ;;
    # --start)
    -command=start)
      echo '**start**'
      sleep 5
      exit 0
      ;;
    # --changemesh)
    -command=changemesh)
      echo '**changemesh**'
      sleep 5
      exit 0
      ;;
    # --scan)
    -command=scan)
      echo "**scan**"
      # shift
      # devicecode=$(echo "$1" | awk -F= '{print $2}')
      # shift
      # factorycode=$(echo "$1" | awk -F= '{print $2}')
      for i in {1..100}; do
      mysql -p123456 -e "INSERT ge.testdatas(device_type, factory, fw_version, rssi_ble, rssi_wifi, mac_ble, mac_wifi, is_qualified, is_sync, datetime) VALUES(1, 1, '3.1', -65, -33, 'scantest', 'scantest', true, false, now())"
      if [ $i -eq 5 ]; then
      mysql -p123456 -e "INSERT ge.testdatas(device_type, factory, fw_version, rssi_ble, rssi_wifi, mac_ble, mac_wifi, is_qualified, is_sync, datetime) VALUES(1, 1, '3.1', -65, -33, 'scantest', 'scantest', false, false, now())"
      fi
      done
      sleep 5
      exit 0
      ;;
    # turn on
    -command=on)
      shift
      mac=$(echo "$1" | awk -F= '{print $2}')
      sleep 1
      echo "**turn on $mac**"
      exit 0
      ;;
    # turn off
    -command=off)
      shift
      mac=$(echo "$1" | awk -F= '{print $2}')
      sleep 2
      echo "**turn off $mac**"
      exit 0
      ;;

    *)
      # continue
      shift
      ;;
  esac
  shift || true
done

printf "Invalid input\n"
printf "${usage}"
exit 1
